#!/bin/sh
pkill -f /tmp/stupidsamba 2>/dev/null
sleep 0.5
/tmp/stupidsamba -config /tmp/smbtest/cfg.yaml > /tmp/smbtest/srv.log 2>&1 &
SRV=$!
sleep 1
W=/tmp/smbtest
run() {
  echo "########## $1 ##########"
  smbclient "//127.0.0.1/public" -p 4555 -U testuser%testpass123 -m SMB3 -c "$2" > /tmp/smbtest/cli.out 2>&1
  echo "rc=$?"
  cat /tmp/smbtest/cli.out
}
run "A single get" 'get hello.txt /tmp/smbtest/got-hello.txt'
run "B semicolon ls;get" 'ls; get hello.txt /tmp/smbtest/got-hello.txt'
run "C newline ls then get" 'ls
get hello.txt /tmp/smbtest/got-hello.txt'
run "D get then ls" 'get hello.txt /tmp/smbtest/got-hello.txt; ls'
kill $SRV 2>/dev/null
